name: C/C++ CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v2
            - name: dir
              run: dir "C:\Program Files (x86)\Microsoft Visual Studio"
